-- Add migration script here
CREATE TABLE TBL_ORGANIZATIONS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    NAME VARCHAR(255) NOT NULL,
    SLUG VARCHAR(255) NOT NULL,
    PLAN VARCHAR(50) NOT NULL,
    LOGO_URL TEXT,
    WEBSITE TEXT,
    SSO_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    MAX_WORKSPACES INTEGER NOT NULL DEFAULT 5,
    MAX_MEMBERS INTEGER NOT NULL DEFAULT 10,
    MAX_CONNECTIONS INTEGER NOT NULL DEFAULT 10,
    AI_CREDITS_LIMIT INTEGER NOT NULL DEFAULT 1000,
    AI_CREDITS_USED INTEGER NOT NULL DEFAULT 0,
    TRIAL_ENDS_AT TIMESTAMPTZ,
    CREATED_BY UUID NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_BY UUID,
    UPDATED_AT TIMESTAMPTZ,
    IS_SOFT_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_BY UUID,
    DELETED_AT TIMESTAMPTZ
);

CREATE UNIQUE INDEX UQ_ORGANIZATIONS_SLUG
    ON TBL_ORGANIZATIONS (LOWER(SLUG))
    WHERE IS_SOFT_DELETED = FALSE;

CREATE TABLE TBL_ORGANIZATION_MEMBERS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    ORG_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    JOINED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CREATED_BY UUID NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_BY UUID,
    UPDATED_AT TIMESTAMPTZ,
    IS_SOFT_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_BY UUID,
    DELETED_AT TIMESTAMPTZ,
    CONSTRAINT FK_ORGANIZATION_MEMBERS_ORG FOREIGN KEY (ORG_ID) REFERENCES TBL_ORGANIZATIONS(ID),
    CONSTRAINT FK_ORGANIZATION_MEMBERS_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(ID),
    CONSTRAINT CK_ORGANIZATION_MEMBERS_ROLE CHECK (ROLE IN ('owner', 'admin', 'member'))
);
CREATE UNIQUE INDEX UQ_ORGANIZATION_MEMBERS_ACTIVE
    ON TBL_ORGANIZATION_MEMBERS (ORG_ID, USER_ID)
    WHERE IS_SOFT_DELETED = FALSE
      AND DELETED_AT IS NULL;
CREATE INDEX IDX_ORGANIZATION_MEMBERS_ORG
    ON TBL_ORGANIZATION_MEMBERS (ORG_ID)
    WHERE IS_SOFT_DELETED = FALSE
      AND DELETED_AT IS NULL;

CREATE TABLE TBL_ORGANIZATION_INVITATIONS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    ORG_ID UUID NOT NULL,

    EMAIL VARCHAR(320) NOT NULL,

    ROLE VARCHAR(50) NOT NULL,

    INVITED_BY UUID NOT NULL,

    TOKEN VARCHAR(255) NOT NULL,

    EXPIRES_AT TIMESTAMPTZ NOT NULL,

    ACCEPTED_AT TIMESTAMPTZ,
    ACCEPTED_BY UUID,

    REVOKED_AT TIMESTAMPTZ,

    CREATED_BY UUID NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UPDATED_BY UUID,
    UPDATED_AT TIMESTAMPTZ,

    IS_SOFT_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_BY UUID,
    DELETED_AT TIMESTAMPTZ,

    CONSTRAINT FK_ORG_INVITATIONS_ORG
        FOREIGN KEY (ORG_ID)
        REFERENCES TBL_ORGANIZATIONS(ID),

    CONSTRAINT FK_ORG_INVITATIONS_INVITED_BY
        FOREIGN KEY (INVITED_BY)
        REFERENCES TBL_USERS(ID),

    CONSTRAINT FK_ORG_INVITATIONS_ACCEPTED_BY
        FOREIGN KEY (ACCEPTED_BY)
        REFERENCES TBL_USERS(ID),

    CONSTRAINT CK_ORG_INVITATIONS_ROLE
        CHECK (ROLE IN ('owner', 'admin', 'member'))
);

CREATE UNIQUE INDEX UQ_ORG_INVITATIONS_TOKEN
    ON TBL_ORGANIZATION_INVITATIONS (TOKEN);