-- Add migration script here

CREATE TABLE TBL_CONNECTION_PERMISSIONS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),

    CONNECTION_ID UUID NOT NULL,
    USER_ID UUID,

    ALLOW_SELECT BOOLEAN NOT NULL DEFAULT TRUE,
    ALLOW_INSERT BOOLEAN NOT NULL DEFAULT FALSE,
    ALLOW_UPDATE BOOLEAN NOT NULL DEFAULT FALSE,
    ALLOW_DELETE BOOLEAN NOT NULL DEFAULT FALSE,
    ALLOW_DDL BOOLEAN NOT NULL DEFAULT FALSE
);

-- One permission record per specific user on a connection
CREATE UNIQUE INDEX UQ_CONNECTION_PERMISSIONS_USER
    ON TBL_CONNECTION_PERMISSIONS (CONNECTION_ID, USER_ID)
    WHERE USER_ID IS NOT NULL;

-- One default permission record per connection
-- USER_ID = NULL means the connection-wide default
CREATE UNIQUE INDEX UQ_CONNECTION_PERMISSIONS_DEFAULT
    ON TBL_CONNECTION_PERMISSIONS (CONNECTION_ID)
    WHERE USER_ID IS NULL;

-- Supports permission lookup
CREATE INDEX IDX_CONNECTION_PERMISSIONS_LOOKUP
    ON TBL_CONNECTION_PERMISSIONS (CONNECTION_ID, USER_ID);