-- Add migration script here
CREATE TABLE TBL_WORKSPACE_MEMBERS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    WORKSPACE_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    JOINED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CREATED_BY UUID NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_BY UUID,
    UPDATED_AT TIMESTAMPTZ,
    IS_SOFT_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_BY UUID,
    DELETED_AT TIMESTAMPTZ,
    CONSTRAINT FK_WORKSPACE_MEMBERS_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES TBL_WORKSPACES(ID),
    CONSTRAINT FK_WORKSPACE_MEMBERS_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(ID)
);