-- Add migration script here
CREATE TABLE TBL_OUTBOX_EVENTS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    EVENT_TYPE TEXT NOT NULL,
    PAYLOAD JSONB NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'pending',
    ATTEMPTS INTEGER NOT NULL DEFAULT 0,
    LAST_ERROR TEXT,
    SCHEDULED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PROCESSED_AT TIMESTAMPTZ,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    IS_SOFT_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_AT TIMESTAMPTZ
);

CREATE INDEX IDX_OUTBOX_PENDING
    ON TBL_OUTBOX_EVENTS(SCHEDULED_AT)
    WHERE STATUS = 'pending';