-- Add migration script here

CREATE TABLE TBL_QUERY_HISTORY (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),

    ORGANIZATION_ID UUID NOT NULL,
    WORKSPACE_ID UUID NOT NULL,
    CONNECTION_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,

    QUERY_TEXT TEXT NOT NULL,
    QUERY_HASH VARCHAR(128) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,

    REJECTION_REASON TEXT,
    DURATION_MS BIGINT,
    ROWS_AFFECTED BIGINT,
    ERROR_MESSAGE TEXT,

    EXECUTED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CREATED_BY UUID NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UPDATED_BY UUID,
    UPDATED_AT TIMESTAMPTZ,

    IS_SOFT_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_BY UUID,
    DELETED_AT TIMESTAMPTZ,

    CONSTRAINT TBL_QUERY_HISTORY_STATUS_CHK
        CHECK (STATUS IN ('success', 'error', 'rejected', 'cancelled')),

    CONSTRAINT TBL_QUERY_HISTORY_DURATION_CHK
        CHECK (DURATION_MS IS NULL OR DURATION_MS >= 0),

    CONSTRAINT TBL_QUERY_HISTORY_ROWS_AFFECTED_CHK
        CHECK (ROWS_AFFECTED IS NULL OR ROWS_AFFECTED >= 0)
);

CREATE INDEX IDX_QUERY_HISTORY_WORKSPACE_ACTIVE
    ON TBL_QUERY_HISTORY (WORKSPACE_ID, EXECUTED_AT DESC)
    WHERE IS_SOFT_DELETED = FALSE
      AND DELETED_AT IS NULL;

CREATE INDEX IDX_QUERY_HISTORY_CONNECTION
    ON TBL_QUERY_HISTORY (CONNECTION_ID, EXECUTED_AT DESC);

CREATE INDEX IDX_QUERY_HISTORY_USER
    ON TBL_QUERY_HISTORY (USER_ID, EXECUTED_AT DESC);

CREATE INDEX IDX_QUERY_HISTORY_ORGANIZATION
    ON TBL_QUERY_HISTORY (ORGANIZATION_ID, EXECUTED_AT DESC);