-- Add migration script here
CREATE TABLE TBL_WORKSPACES (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    ORGANIZATION_ID UUID NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    COLOR VARCHAR(50),

    CREATED_BY UUID NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_BY UUID,
    UPDATED_AT TIMESTAMPTZ,

    IS_SOFT_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_BY UUID,
    DELETED_AT TIMESTAMPTZ
);